declaration:
  call: declare
  version: 0.1
  description: "Decription placeholder for 'TRAINED-MODEL'"
  method: post
  accepts: json
  returns: json
  namespace: model
  allowlist:
    body:
      - field: versionNumber
        type: string
        description: "Body field 'versionNumber'"
      - field: name
        type: string
        description: "Trained model file name"  

getModelByFilenameFromDb:
  call: http.post
  args:
    url: "[#TRAINING_RESQL]/training/get_llm_model"
    body:
      fileName: ${incoming.body.name}
  result: dbResult

updateInDatabase:
  call: http.post
  args:
    url: "[#TRAINING_RESQL]/training/create_llm_trainings"
    body:
      model_type: ${dbResult.response.body[0].modelType}
      state: "ACTIVATING"
      file_name: ${dbResult.response.body[0].fileName}
      version_number: ${dbResult.response.body[0].versionNumber}
      model_version: ${dbResult.response.body[0].modelVersion}
      test_report: ${dbResult.response.body[0].testReport}
      cross_validation_report: ${dbResult.response.body[0].crossValidationReport}
      trained_date: ${dbResult.response.body[0].trainedDate}
      training_data_checksum: ""
  result: dbModelResult

loadTrainedModel:
  call: http.post
  args:
    url: "[#CRON_INSTANCE]/execute/load_trained_model/load_trained_model_now?versionNumber=${incoming.body.versionNumber}"
  next: returnSuccess

returnSuccess:
  return: "Model copied and loaded successfully"
  wrapper: false
  next: end
