-- liquibase formatted sql

-- changeset liquibase:1719303819092
CREATE TYPE trigger_status AS ENUM ('pending','deleted', 'declined', 'approved');

CREATE TYPE author_role AS ENUM ('trainer', 'service_manager', 'admin');

CREATE EXTENSION IF NOT EXISTS hstore;

CREATE TABLE "intent" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "intent" VARCHAR(250) NOT NULL, "status" VARCHAR(10) NOT NULL, "created" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, CONSTRAINT "intent_pkey" PRIMARY KEY ("id"));

CREATE TABLE "llm_trainings" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "model_type" VARCHAR(30) NOT NULL, "state" VARCHAR(30) NOT NULL, "trained_date" TIMESTAMP WITH TIME ZONE NOT NULL, "file_name" VARCHAR(100) DEFAULT 'rasa_1_0', "version_number" VARCHAR(20) DEFAULT '1_0', "model_version" VARCHAR(40) DEFAULT 'riaee/byk:loba-bot-v0.2', "test_report" TEXT, "created" TIMESTAMP WITH TIME ZONE NOT NULL, "cross_validation_report" TEXT, "training_data_checksum" VARCHAR(64), CONSTRAINT "llm_trainings_pkey" PRIMARY KEY ("id"));

CREATE TABLE "service_trigger" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "intent" VARCHAR(250) NOT NULL, "service" VARCHAR(250) NOT NULL, "status" TRIGGER_STATUS DEFAULT 'pending' NOT NULL, "author_role" AUTHOR_ROLE DEFAULT 'trainer' NOT NULL, "created" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, "service_name" VARCHAR(250) NOT NULL, CONSTRAINT "service_trigger_pkey" PRIMARY KEY ("id"));

CREATE TABLE "train_settings" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "rasa_folds" INTEGER NOT NULL, "scheduled" BOOLEAN NOT NULL, "days_of_week" VARCHAR(15), "from_date" TIMESTAMP WITH TIME ZONE, "last_modified" TIMESTAMP WITH TIME ZONE NOT NULL, "modifier_id" VARCHAR(30) NOT NULL, "modifier_name" VARCHAR(50) NOT NULL, CONSTRAINT "train_settings_pkey" PRIMARY KEY ("id"));

INSERT INTO "train_settings" ("id", "rasa_folds", "scheduled", "days_of_week", "from_date", "last_modified", "modifier_id", "modifier_name") VALUES (1, 8, TRUE, '1', '2024-06-25 08:22:52.236628', '2024-06-25 08:22:52.236628', '111111111', 'Vassili M');

