FROM node:22.5.1-alpine AS development

ARG user=user
ARG uid=10001
ARG gid=20000
USER root
RUN addgroup -g ${gid} -S ${user}
RUN adduser -u ${uid} -g ${gid} -S ${user} -G ${user}
USER ${user}

ENV NODE_ENV development
ENV PORT=3010

WORKDIR /app
COPY ./package.json .

RUN npm install --legacy-peer-deps
COPY . .
RUN ./node_modules/.bin/vite build --mode=development

RUN chown ${uid}:${gid} /app

EXPOSE 3001

ENV REACT_APP_ENABLE_HIDDEN_FEATURES TRUE

CMD ["npm", "run", "dev"]
