declaration:
  call: declare
  version: 0.1
  description: "Decription placeholder for 'TRAINED-MODEL'"
  method: post
  accepts: json
  returns: json
  namespace: model
  allowlist:
    body:
      - field: versionNumber
        type: string
        description: "Body field 'versionNumber'"

loadTrainedModel:
  call: http.post
  args:
    url: "[#CRON_INSTANCE]/execute/load_trained_model/load_trained_model_now?versionNumber=${incoming.body.versionNumber}"
  next: returnSuccess

returnSuccess:
  return: "Model copied and loaded successfully"
  wrapper: false
  next: end
