assign_values:
  assign:
    input: ${incoming.body}
  next: getFileLocations

getFileLocations:
  call: http.get
  args:
    url: "[#TRAINING_PUBLIC_RUUTER]/return-file-locations"
    headers:
      cookie: ${incoming.headers.cookie}
  result: fileLocations

convertJsonToYaml:
  call: http.post
  args:
    url: "[#TRAINING_DMAPPER]/convert/json-to-yaml"
    body:
      recipe: ${input.recipe}
      language: ${input.language}
      pipeline: ${input.pipeline}
      policies: ${input.policies}
  result: configYaml

saveConfigFile:
  call: http.post
  args:
    url: "[#TRAINING_DMAPPER]/file/write"
    body:
      file_path: ${fileLocations.response.body.response.config_location}
      content: ${configYaml.response.body.json}
  result: fileResult
  next: returnSuccess

returnSuccess:
  return: "Config updated"
  next: end

returnUnauthorized:
  return: "error: unauthorized"
  next: end
