declaration:
  call: declare
  version: 0.1
  description: "Decription placeholder for 'SETTINGS'"
  method: get
  accepts: json
  returns: json
  namespace: training

getFromDatabase:
  call: http.get
  args:
    url: "[#TRAINING_RESQL]/llm/get_train_settings"
  result: dbResult

validateDbRecords:
  switch:
    - condition: ${dbResult.response.body.length !== 0}
      next: returnSuccess
  next: returnError

returnSuccess:
  return: ${dbResult.response.body[0]}
  wrapper: false
  next: end

returnError:
  return: "Can't find train settings record."
  status: 409
  next: end
