declaration:
  call: declare
  version: 0.1
  description: "Decription placeholder for 'TRAINED'"
  method: get
  accepts: json
  returns: json
  namespace: training

getFromDatabase:
  call: http.post
  args:
    url: "[#TRAINING_RESQL]/get-latest-ready-model"
  result: dbResult

validateDbRecords:
  switch:
    - condition: ${dbResult.response.body.length !== 0}
      next: returnSuccess
  next: returnError

returnSuccess:
  return: ${dbResult.response.body[0]}
  wrapper: false
  next: end

returnError:
  return: "Can't find trained model record."
  status: 409
  next: end
